version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: cgrd
      MYSQL_DATABASE: cgrd
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'

  php:
    container_name: php
    build:
      context: ./
    ports:
      - '9000:9000'
    env_file:
      - ../app/.env
    volumes:
      - ../app:/var/www/cgrd
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:1.25.2-alpine
    ports:
      - '8080:80'
    volumes:
      - ../app:/var/www/cgrd
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql